#!/usr/bin/env python3
"""Render coverage of source-specimen rows, not distinct sequencing profiles."""
import argparse
import csv
import hashlib
import json
from collections import defaultdict
from pathlib import Path

FIELDS = ("kg_sample_eligible", "dna_expected_by_generator", "has_sra_run", "in_feature_table", "in_ecology_analysis")


def coverage(path):
    counts = defaultdict(lambda: [0] * len(FIELDS))
    with path.open() as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            if row["is_control"] == "True" or row["compartment"] not in ("Surface", "Deep", "Rhizosphere"):
                continue
            values = counts[(row["trip"], row["compartment"])]
            for index, field in enumerate(FIELDS):
                if row[field] not in ("True", "False"):
                    raise ValueError(f"Invalid boolean in {field}: {row[field]}")
                values[index] += row[field] == "True"
    return sorted(counts.items())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    rows = coverage(args.ledger)
    labels = {"Surface": "Surface", "Deep": "Subsurface", "Rhizosphere": "Root-adjacent"}
    text = ["% Generated by scripts/manuscript/generate_sample_coverage.py", r"\begin{tabular}{llrrrrr}", r"\toprule",
            r"Trip & Compartment & Specimens & Extract-linked & Run-linked & ASV table & Ecology \\", r"\midrule"]
    for (trip, compartment), values in rows:
        text.append(f"{trip.removeprefix('Trip')} & {labels[compartment]} & " + " & ".join(map(str, values)) + r" \\")
    text += [r"\bottomrule", r"\end{tabular}"]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(text) + "\n")
    manifest = {"unit": "non-control source-specimen rows in three soil compartments", "fields": FIELDS,
                "input_sha256": hashlib.sha256(args.ledger.read_bytes()).hexdigest(),
                "output_sha256": hashlib.sha256(args.output.read_bytes()).hexdigest(),
                "exclusions": "control rows and rows outside Surface, Deep, Rhizosphere; no site-range restriction"}
    args.output.with_suffix(".json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    main()
