mappings:
  LE: http://purl.obolibrary.org/obo/CHEBI_24431
  Si: http://purl.obolibrary.org/obo/CHEBI_27573
  Fe: http://purl.obolibrary.org/obo/CHEBI_18248
  Ca: http://purl.obolibrary.org/obo/CHEBI_22984
  K: http://purl.obolibrary.org/obo/CHEBI_18019
  S: http://purl.obolibrary.org/obo/CHEBI_17115
  P: http://purl.obolibrary.org/obo/CHEBI_17203
  Ti: http://purl.obolibrary.org/obo/CHEBI_33341
  Al: http://purl.obolibrary.org/obo/CHEBI_28984
  Mg: http://purl.obolibrary.org/obo/CHEBI_25107
  Na: http://purl.obolibrary.org/obo/CHEBI_26708
  Cl: http://purl.obolibrary.org/obo/CHEBI_23116
  Mn: http://purl.obolibrary.org/obo/CHEBI_18291
  Sr: http://purl.obolibrary.org/obo/CHEBI_33324
  Zr: http://purl.obolibrary.org/obo/CHEBI_33342
  V: http://purl.obolibrary.org/obo/CHEBI_16414
  Cr: http://purl.obolibrary.org/obo/CHEBI_28073
  Ba: http://purl.obolibrary.org/obo/CHEBI_32594
  Pb: http://purl.obolibrary.org/obo/CHEBI_25016
  Zn: http://purl.obolibrary.org/obo/CHEBI_27363
  Cu: http://purl.obolibrary.org/obo/CHEBI_28694
  Ni: http://purl.obolibrary.org/obo/CHEBI_28112
  Co: http://purl.obolibrary.org/obo/CHEBI_27638
  As: http://purl.obolibrary.org/obo/CHEBI_27563
  U: http://purl.obolibrary.org/obo/CHEBI_17568
  Th: http://purl.obolibrary.org/obo/CHEBI_33385
  Rb: http://purl.obolibrary.org/obo/CHEBI_33322
  Y: http://purl.obolibrary.org/obo/CHEBI_17895
  Nb: http://purl.obolibrary.org/obo/CHEBI_33344
  Mo: http://purl.obolibrary.org/obo/CHEBI_28685
  Ag: http://purl.obolibrary.org/obo/CHEBI_30512
  Cd: http://purl.obolibrary.org/obo/CHEBI_22977
  Sn: http://purl.obolibrary.org/obo/CHEBI_17909
  Sb: http://purl.obolibrary.org/obo/CHEBI_30513
  I: http://purl.obolibrary.org/obo/CHEBI_17191
  Cs: http://purl.obolibrary.org/obo/CHEBI_30514
  La: http://purl.obolibrary.org/obo/CHEBI_33336
  Ce: http://purl.obolibrary.org/obo/CHEBI_33369
  Pr: http://purl.obolibrary.org/obo/CHEBI_26308
  Nd: http://purl.obolibrary.org/obo/CHEBI_33372
  Sm: http://purl.obolibrary.org/obo/CHEBI_33374
  Eu: http://purl.obolibrary.org/obo/CHEBI_32999
  Gd: http://purl.obolibrary.org/obo/CHEBI_33375
  Tb: http://purl.obolibrary.org/obo/CHEBI_33376
  Dy: http://purl.obolibrary.org/obo/CHEBI_33377
  Ho: http://purl.obolibrary.org/obo/CHEBI_49648
  Er: http://purl.obolibrary.org/obo/CHEBI_33379
  Tm: http://purl.obolibrary.org/obo/CHEBI_33380
  Yb: http://purl.obolibrary.org/obo/CHEBI_33381
  Lu: http://purl.obolibrary.org/obo/CHEBI_33382
  Hf: http://purl.obolibrary.org/obo/CHEBI_33343
  Ta: http://purl.obolibrary.org/obo/CHEBI_33348
  W: http://purl.obolibrary.org/obo/CHEBI_16828
  Re: http://purl.obolibrary.org/obo/CHEBI_49882
  Os: http://purl.obolibrary.org/obo/CHEBI_30687
  Ir: http://purl.obolibrary.org/obo/CHEBI_49666
  Pt: http://purl.obolibrary.org/obo/CHEBI_33364
  Au: http://purl.obolibrary.org/obo/CHEBI_29287
  Hg: http://purl.obolibrary.org/obo/CHEBI_16170
  Bi: http://purl.obolibrary.org/obo/CHEBI_33301
  Sc: http://purl.obolibrary.org/obo/CHEBI_33330
  Br: http://purl.obolibrary.org/obo/CHEBI_22927
  Ga: http://purl.obolibrary.org/obo/CHEBI_49631
  Se: http://purl.obolibrary.org/obo/CHEBI_27568
  Ge: http://purl.obolibrary.org/obo/CHEBI_30441
  SiO2: http://purl.obolibrary.org/obo/CHEBI_30563
  Fe2O3: http://purl.obolibrary.org/obo/CHEBI_50819
  Al2O3: http://purl.obolibrary.org/obo/CHEBI_30187
  CaO: http://purl.obolibrary.org/obo/CHEBI_31344
  MgO: http://purl.obolibrary.org/obo/CHEBI_31794
  K2O: http://purl.obolibrary.org/obo/CHEBI_88321
  Na2O: null
  TiO2: http://purl.obolibrary.org/obo/CHEBI_32234
  MnO: null
  P2O5: http://purl.obolibrary.org/obo/CHEBI_37376
  SO3: http://purl.obolibrary.org/obo/CHEBI_17359
  Cr2O3: http://purl.obolibrary.org/obo/CHEBI_48242
  V2O5: http://purl.obolibrary.org/obo/CHEBI_30045
  ZnO: http://purl.obolibrary.org/obo/CHEBI_36560
  SrO: null
  ZrO2: null
  BaO: null
  La2O3: null
  CeO2: http://purl.obolibrary.org/obo/CHEBI_79089
  PrO2: null
  Nd2O3: null
  Sm2O3: null
  CuO: http://purl.obolibrary.org/obo/CHEBI_75955
  NiO: null
  CoO: null
  PbO: http://purl.obolibrary.org/obo/CHEBI_81045
  Sc2O3: null
  Ga2O3: null
