#!/usr/bin/env python3
"""Audit the canonical SILVA-to-NCBI taxonomy mapping.

The project contains two historically different mapping products.  The
canonical table for the data release is ``mapped_taxonomy.tsv``; a later
mixed-resource JSON file was generated by a lexical index and is not assumed
to be equivalent.  This audit checks every explicit NCBI identifier in the
TSV against the pinned NCBI Taxonomy OWL source and detects project-local
identifiers that have been reused in incompatible lineage contexts.

The implementation is streaming with respect to the large NCBI OWL file:
only records for identifiers used by the mapping table are retained.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import tempfile
import unicodedata
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Iterable

from xml.etree import ElementTree as etree

try:
    from scripts.taxonomy.ncbi_index import build_ncbi_index
except ModuleNotFoundError:  # Direct invocation from a staged script folder.
    build_ncbi_index = None  # type: ignore[assignment]


RANKS = ("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
EXPECTED_NCBI_RANK = {
    "Kingdom": {"superkingdom", "domain"},
    "Phylum": {"phylum"},
    "Class": {"class"},
    "Order": {"order"},
    "Family": {"family"},
    "Genus": {"genus"},
    "Species": {"species"},
}
NCBI_PREFIX = "http://purl.obolibrary.org/obo/NCBITaxon_"
OWL_CLASS = "{http://www.w3.org/2002/07/owl#}Class"
RDF_ABOUT = "{http://www.w3.org/1999/02/22-rdf-syntax-ns#}about"
RDF_RESOURCE = "{http://www.w3.org/1999/02/22-rdf-syntax-ns#}resource"
RDFS_LABEL = "{http://www.w3.org/2000/01/rdf-schema#}label"
NCBI_RANK = "{http://purl.obolibrary.org/obo/ncbitaxon#}has_rank"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def norm_label(value: str) -> str:
    value = unicodedata.normalize("NFKC", value).strip().lower()
    value = re.sub(r"^[dpcofgs]__", "", value)
    value = re.sub(r'^["\']|["\']$', "", value)
    value = re.sub(r"^(?:candidatus|ca\.)\s+", "", value)
    value = re.sub(r"\s+", " ", value)
    return value


def as_bool(value: str) -> bool:
    value = value.strip().lower()
    if value not in {"true", "false"}:
        raise ValueError(f"expected True/False, found {value!r}")
    return value == "true"


@dataclass
class MappingRow:
    taxon_string: str
    rank: str
    name: str
    mapped_id: str
    is_rak: bool
    is_inherited: bool
    parent_mapped_id: str | None = None
    expected_label: str | None = None


@dataclass
class NcbiRecord:
    identifier: str
    label: str | None = None
    rank: str | None = None
    parent: str | None = None
    synonyms: set[str] = field(default_factory=set)

    @property
    def normalized_names(self) -> set[str]:
        values = set(self.synonyms)
        if self.label:
            values.add(self.label)
        return {norm_label(value) for value in values}


def read_mapping(path: Path) -> list[MappingRow]:
    rows: list[MappingRow] = []
    last_explicit: dict[str, str] = {}
    genus_by_taxon: dict[str, str] = {}
    seen_ranks: dict[str, list[str]] = defaultdict(list)

    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {
            "Taxon String",
            "Rank",
            "Name",
            "Mapped ID",
            "Is RAK",
            "Is Inherited",
        }
        if set(reader.fieldnames or ()) != required:
            raise ValueError(
                f"{path}: expected columns {sorted(required)}, "
                f"found {reader.fieldnames}"
            )
        for raw in reader:
            rank = raw["Rank"].strip()
            if rank not in RANKS:
                raise ValueError(f"{path}: unexpected rank {rank!r}")
            taxon_string = raw["Taxon String"]
            row = MappingRow(
                taxon_string=taxon_string,
                rank=rank,
                name=raw["Name"].strip(),
                mapped_id=raw["Mapped ID"].strip(),
                is_rak=as_bool(raw["Is RAK"]),
                is_inherited=as_bool(raw["Is Inherited"]),
                parent_mapped_id=last_explicit.get(taxon_string),
            )
            seen_ranks[taxon_string].append(rank)
            if rank == "Genus":
                genus_by_taxon[taxon_string] = row.name
            if not row.is_inherited:
                last_explicit[taxon_string] = row.mapped_id
            rows.append(row)

    for row in rows:
        if row.rank != "Species" or row.is_inherited:
            row.expected_label = row.name
            continue
        species = row.name
        genus = genus_by_taxon.get(row.taxon_string, "")
        if " " in species or not genus or genus.upper() == "NA":
            row.expected_label = species
        else:
            row.expected_label = f"{genus} {species}"
    return rows


def iter_ncbi_records(path: Path, wanted: set[str]) -> dict[str, NcbiRecord]:
    records: dict[str, NcbiRecord] = {}
    parser = etree.iterparse(str(path), events=("start", "end"))
    stack: list[etree.Element] = []
    root: etree.Element | None = None
    for event, element in parser:
        if event == "start":
            stack.append(element)
            if root is None:
                root = element
            continue
        if element.tag == OWL_CLASS:
            about = element.get(RDF_ABOUT, "")
            if about.startswith(NCBI_PREFIX):
                identifier = about.removeprefix(NCBI_PREFIX)
                if identifier in wanted:
                    record = NcbiRecord(identifier=identifier)
                    for child in element:
                        local_name = child.tag.rsplit("}", 1)[-1]
                        if child.tag == RDFS_LABEL and child.text:
                            record.label = child.text.strip()
                        elif child.tag == NCBI_RANK:
                            resource = child.get(RDF_RESOURCE, "")
                            record.rank = resource.rsplit("_", 1)[-1].lower()
                        elif (
                            child.tag.rsplit("}", 1)[-1] == "subClassOf"
                            and child.get(RDF_RESOURCE, "").startswith(
                                NCBI_PREFIX
                            )
                        ):
                            record.parent = child.get(
                                RDF_RESOURCE, ""
                            ).removeprefix(NCBI_PREFIX)
                        elif (
                            local_name.lower().endswith("synonym")
                            and child.text
                        ):
                            record.synonyms.add(child.text.strip())
                    records[identifier] = record
        if len(stack) == 2 and root is not None:
            # The ontology consists of millions of direct children.  Removing
            # each completed child keeps memory bounded while retaining all
            # nested data until its enclosing Class has been inspected.
            root.remove(element)
        stack.pop()
    return records


def violation(
    code: str,
    row: MappingRow | None,
    detail: str,
) -> dict[str, str]:
    result = {"code": code, "detail": detail}
    if row is not None:
        result.update(
            {
                "taxon_string": row.taxon_string,
                "rank": row.rank,
                "name": row.name,
                "mapped_id": row.mapped_id,
            }
        )
    return result


def audit_rows(
    rows: Iterable[MappingRow],
    ncbi_records: dict[str, NcbiRecord],
    is_descendant: Callable[[str, str], bool] | None = None,
) -> list[dict[str, str]]:
    rows = list(rows)
    violations: list[dict[str, str]] = []

    ranks_by_taxon: dict[str, list[str]] = defaultdict(list)
    first_row_by_taxon: dict[str, MappingRow] = {}
    for row in rows:
        ranks_by_taxon[row.taxon_string].append(row.rank)
        first_row_by_taxon.setdefault(row.taxon_string, row)
    for taxon_string, observed_ranks in ranks_by_taxon.items():
        if tuple(observed_ranks) != RANKS:
            violations.append(
                violation(
                    "mapping_rank_sequence",
                    first_row_by_taxon[taxon_string],
                    f"expected ordered ranks {list(RANKS)}, found "
                    f"{observed_ranks}",
                )
            )

    explicit_ncbi = [
        row for row in rows if not row.is_rak and not row.is_inherited
    ]
    identity_valid: set[tuple[str, str, str]] = set()
    for row in explicit_ncbi:
        record = ncbi_records.get(row.mapped_id)
        if record is None:
            violations.append(
                violation(
                    "ncbi_identifier_missing",
                    row,
                    "identifier is absent from the pinned NCBI Taxonomy OWL",
                )
            )
            continue
        row_valid = True
        expected_ranks = EXPECTED_NCBI_RANK[row.rank]
        if record.rank not in expected_ranks:
            row_valid = False
            violations.append(
                violation(
                    "ncbi_rank_mismatch",
                    row,
                    f"expected {sorted(expected_ranks)}, found {record.rank!r} "
                    f"({record.label!r})",
                )
            )
        expected_label = norm_label(row.expected_label or row.name)
        if expected_label not in record.normalized_names:
            row_valid = False
            violations.append(
                violation(
                    "ncbi_label_mismatch",
                    row,
                    f"expected preferred label or synonym "
                    f"{row.expected_label!r}, found preferred label "
                    f"{record.label!r}",
                )
            )
        if row_valid:
            identity_valid.add(
                (row.taxon_string, row.rank, row.mapped_id)
            )

    local_contexts: dict[
        str, set[tuple[str, str, str | None]]
    ] = defaultdict(set)
    for row in rows:
        if row.is_rak and not row.is_inherited:
            local_contexts[row.mapped_id].add(
                (row.rank, row.name, row.parent_mapped_id)
            )
    for identifier, contexts in sorted(local_contexts.items()):
        if len(contexts) > 1:
            violations.append(
                violation(
                    "project_identifier_context_collision",
                    None,
                    f"{identifier} is reused in {len(contexts)} contexts: "
                    + "; ".join(
                        f"{rank}|{name}|parent={parent}"
                        for rank, name, parent in sorted(
                            contexts, key=lambda item: tuple(
                                "" if part is None else part for part in item
                            )
                        )
                    ),
                )
            )
    if is_descendant is not None:
        by_taxon: dict[str, list[MappingRow]] = defaultdict(list)
        for row in rows:
            by_taxon[row.taxon_string].append(row)
        for taxon_rows in by_taxon.values():
            nearest_valid_ancestor: MappingRow | None = None
            for row in taxon_rows:
                key = (row.taxon_string, row.rank, row.mapped_id)
                if row.is_rak or row.is_inherited or key not in identity_valid:
                    continue
                if (
                    nearest_valid_ancestor is not None
                    and not is_descendant(
                        row.mapped_id, nearest_valid_ancestor.mapped_id
                    )
                ):
                    violations.append(
                        violation(
                            "ncbi_ancestry_mismatch",
                            row,
                            f"NCBITaxon_{row.mapped_id} is not a descendant "
                            f"of preceding validated "
                            f"NCBITaxon_{nearest_valid_ancestor.mapped_id} "
                            f"({nearest_valid_ancestor.rank})",
                        )
                    )
                    continue
                nearest_valid_ancestor = row

    explicit_contexts: dict[
        tuple[bool, str], set[tuple[str, str]]
    ] = defaultdict(set)
    for row in rows:
        if not row.is_inherited:
            explicit_contexts[(row.is_rak, row.mapped_id)].add(
                (row.rank, row.name)
            )
    for (is_rak, identifier), contexts in sorted(explicit_contexts.items()):
        if len(contexts) > 1:
            violations.append(
                violation(
                    "explicit_identifier_rank_or_label_collision",
                    None,
                    f"{'RAK' if is_rak else 'NCBI'} {identifier} is reused "
                    f"for {sorted(contexts)}",
                )
            )
    return violations


def write_outputs(
    output_dir: Path,
    mapping_path: Path,
    ncbi_path: Path,
    rows: list[MappingRow],
    records: dict[str, NcbiRecord],
    violations: list[dict[str, str]],
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    by_code: dict[str, int] = defaultdict(int)
    for item in violations:
        by_code[item["code"]] += 1
    explicit_ncbi_ids = {
        row.mapped_id
        for row in rows
        if not row.is_rak and not row.is_inherited
    }
    report = {
        "status": "passed" if not violations else "failed",
        "inputs": {
            "mapping": {
                "path": str(mapping_path),
                "bytes": mapping_path.stat().st_size,
                "sha256": sha256(mapping_path),
            },
            "ncbi_taxonomy": {
                "path": str(ncbi_path),
                "bytes": ncbi_path.stat().st_size,
                "sha256": sha256(ncbi_path),
            },
        },
        "counts": {
            "mapping_rows": len(rows),
            "taxon_strings": len({row.taxon_string for row in rows}),
            "explicit_ncbi_identifiers": len(explicit_ncbi_ids),
            "explicit_ncbi_identifiers_found": len(records),
            "explicit_project_identifiers": len(
                {
                    row.mapped_id
                    for row in rows
                    if row.is_rak and not row.is_inherited
                }
            ),
            "inherited_rows": sum(row.is_inherited for row in rows),
            "violations": len(violations),
        },
        "violations_by_code": dict(sorted(by_code.items())),
        "violations": violations,
        "interpretation": (
            "A failed audit means the mapping must not be used to assert "
            "unqualified external taxon identity. Invalid or ambiguous rows "
            "require curation or lineage-scoped project identifiers."
        ),
    }
    (output_dir / "taxonomy_mapping_audit.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    columns = ("code", "taxon_string", "rank", "name", "mapped_id", "detail")
    with (output_dir / "taxonomy_mapping_violations.tsv").open(
        "w", newline="", encoding="utf-8"
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, delimiter="\t")
        writer.writeheader()
        for item in violations:
            writer.writerow({column: item.get(column, "") for column in columns})


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mapping",
        type=Path,
        default=Path("data/processed/ontology/mapped_taxonomy.tsv"),
    )
    parser.add_argument(
        "--ncbi-taxonomy",
        type=Path,
        default=Path("data/ontologies/ncbitaxon.owl"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/release/taxonomy_mapping_audit"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = read_mapping(args.mapping)
    wanted = {
        row.mapped_id
        for row in rows
        if not row.is_rak and not row.is_inherited
    }
    if build_ncbi_index is None:
        raise SystemExit(
            "ancestry-aware CLI audit requires scripts.taxonomy.ncbi_index"
        )
    wanted_names = {
        row.expected_label or row.name
        for row in rows
        if not row.is_rak and not row.is_inherited
    }
    with tempfile.TemporaryDirectory(prefix="eq-ncbi-audit-") as temp:
        with build_ncbi_index(
            args.ncbi_taxonomy,
            Path(temp) / "ncbi.sqlite",
            wanted_names,
        ) as index:
            records: dict[str, NcbiRecord] = {}
            for identifier in wanted:
                item = index.taxon(identifier)
                if item is None:
                    continue
                records[identifier] = NcbiRecord(
                    identifier=identifier,
                    label=item.label,
                    rank=item.rank,
                    parent=item.parent,
                    synonyms=set(item.names),
                )
            violations = audit_rows(rows, records, index.is_descendant)
    write_outputs(
        args.output_dir,
        args.mapping,
        args.ncbi_taxonomy,
        rows,
        records,
        violations,
    )
    print(
        json.dumps(
            {
                "status": "passed" if not violations else "failed",
                "rows": len(rows),
                "ncbi_ids": len(wanted),
                "violations": len(violations),
                "output": str(args.output_dir / "taxonomy_mapping_audit.json"),
            },
            sort_keys=True,
        )
    )
    return 0 if not violations else 1


if __name__ == "__main__":
    raise SystemExit(main())
